In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r'C:\Users\HP\Downloads\pricedatayes.xlsx')

In [3]:
df1 = df[['Hour','MCP']]

In [4]:
df1

Hour      MCP
0    1.0  2872.97
1    NaN  2872.71
2    NaN  3150.24
3    NaN  3150.31
4    2.0  3039.48
..   ...      ...
91   NaN  2759.79
92  24.0  2080.23
93   NaN  2000.86
94   NaN  1999.78
95   NaN  1999.68

[96 rows x 2 columns]

In [5]:
k = df1.fillna(method = 'ffill')

In [6]:
k

Hour      MCP
0    1.0  2872.97
1    1.0  2872.71
2    1.0  3150.24
3    1.0  3150.31
4    2.0  3039.48
..   ...      ...
91  23.0  2759.79
92  24.0  2080.23
93  24.0  2000.86
94  24.0  1999.78
95  24.0  1999.68

[96 rows x 2 columns]

In [7]:
dfn = k.groupby(['Hour']).mean()

In [8]:
dfn

MCP
Hour            
1.0    3011.5575
2.0    3022.0775
3.0    2822.7350
4.0    2648.3750
5.0    2934.5975
6.0    2227.7200
7.0    4295.9000
8.0    3952.5075
9.0    3929.2525
10.0   3857.0450
11.0   3733.7050
12.0   3254.8150
13.0   3094.9475
14.0   2999.8600
15.0   3140.0975
16.0   3805.2375
17.0   5312.7750
18.0  10187.9200
19.0  15996.9900
20.0   6680.7225
21.0   3450.8550
22.0   3165.4150
23.0   2582.3450
24.0   2020.1375

In [9]:
l = dfn['MCP'].tolist()
nl = np.array(l)

In [10]:
m = np.mean(nl)
m

4255.31625

In [11]:
s = np.std(nl)
s

2952.7633926113745

In [12]:
noise = np.random.normal(m, s, nl.shape)
new_array = nl + noise

In [13]:
price_list = (new_array/new_array.max())*15

In [14]:
price_list

array([ 5.15894104,  1.84827104,  3.3220806 ,  4.48222616,  3.6173171 ,
        0.08771789,  8.64746746,  4.81283383,  8.77861852,  7.03673959,
        4.37419262,  5.44170312,  4.44079546,  2.69305567,  4.72009565,
        3.90335253,  3.45227531,  9.48127887, 15.        ,  5.77512669,
        4.50262367,  4.67505457,  3.12357765,  6.22475087])

In [15]:
B=[2.1]
B_max = 3
B_min = 0.6
B_in = B_out = 1.5
alpha = 0.1416

In [16]:
p_max = 15
gma = (p_max*B_max)/(B_max - B_min)
eps = p_max/(B_max - B_min)

In [17]:
X = []

In [18]:
##Optimal Storage Optimization

In [19]:
for i in range(24):
    b_in = B[i]
    p = price_list[i]
    x = alpha*(gma - eps*b_in - p)
    b = b_in + x
    X.append(x)
    B.append(b)

In [20]:
X

[0.06599394940285931,
 0.47638017483584433,
 -0.15390771295873681,
 -0.18197599840975517,
 0.1015438838407629,
 0.5114687947046478,
 -1.1532416281053997,
 0.4103613351452432,
 -0.5143635593621205,
 0.1874982478416691,
 0.39857894919505615,
 -0.10532290792215039,
 0.12961639018101703,
 0.2623858394953969,
 -0.25685448961051743,
 0.08611255935030791,
 0.07377547801050169,
 -0.8452227233561638,
 -0.8786515253164388,
 1.2051971348099204,
 0.3187840984529566,
 0.012243956179755286,
 0.22109718704667874,
 -0.4136999522652526]

In [21]:
B

[2.1,
 2.1659939494028593,
 2.6423741242387035,
 2.488466411279967,
 2.3064904128702115,
 2.4080342967109742,
 2.919503091415622,
 1.7662614633102223,
 2.1766227984554654,
 1.6622592390933448,
 1.849757486935014,
 2.24833643613007,
 2.1430135282079195,
 2.2726299183889367,
 2.5350157578843335,
 2.278161268273816,
 2.3642738276241237,
 2.4380493056346255,
 1.5928265822784617,
 0.714175056962023,
 1.9193721917719433,
 2.2381562902248997,
 2.250400246404655,
 2.4714974334513338,
 2.057797481186081]

In [22]:
##Quadratic Convex Optimisation

In [23]:
from cvxopt import solvers, matrix

In [24]:
A = np.identity(24, dtype = float)

In [25]:
A.shape

(24, 24)

In [26]:
alpha1 = alpha*24

In [27]:
k = (1/alpha1)*A
k.shape

(24, 24)

In [36]:
A1 = matrix((1/alpha1)*A) ## A1 = P

In [29]:
A1

<24x24 matrix, tc='d'>

In [37]:
B1 = matrix(price_list*(1/24)) ## B1 = q

In [38]:
C = np.array([1.0 for i in range(24)])

In [39]:
C

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [40]:
C.shape

(24,)

In [41]:
C1 = matrix(C, (1, 24)) ## C1 = A

In [42]:
C1

<1x24 matrix, tc='d'>

In [43]:
D1 = matrix([0.0]) ## D1 = b

In [44]:
g = np.identity(24, dtype = float)
g1 = (-1)*np.identity(24, dtype = float)
g2 = np.concatenate((g, g1), axis = 0)
g2

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [-0., -0., -0., ..., -1., -0., -0.],
       [-0., -0., -0., ..., -0., -1., -0.],
       [-0., -0., -0., ..., -0., -0., -1.]])

In [45]:
g2.shape

(48, 24)

In [46]:
G1 = matrix(g2) ## G1 = G
G1

<48x24 matrix, tc='d'>

In [47]:
H1 = matrix([B_in for i in range(48)]) ## H1 = h

In [48]:
H1

<48x1 matrix, tc='d'>

In [49]:
sol = solvers.qp(A1, B1, G1, H1, C1, D1)

     pcost       dcost       gap    pres   dres
 0: -1.4553e-01 -8.4781e+01  8e+01  2e-16  6e-16
 1: -3.5447e-01 -7.2304e+00  7e+00  2e-16  9e-16
 2: -5.8785e-01 -8.8026e-01  3e-01  2e-16  8e-17
 3: -6.0490e-01 -6.1620e-01  1e-02  7e-16  6e-17
 4: -6.0618e-01 -6.0688e-01  7e-04  4e-16  7e-17
 5: -6.0622e-01 -6.0624e-01  2e-05  2e-16  7e-17
 6: -6.0622e-01 -6.0622e-01  2e-07  2e-16  6e-17
Optimal solution found.


In [50]:
print(sol['x'])

[ 1.05e-02]
[ 4.79e-01]
[ 2.71e-01]
[ 1.06e-01]
[ 2.29e-01]
[ 7.29e-01]
[-4.83e-01]
[ 5.95e-02]
[-5.02e-01]
[-2.55e-01]
[ 1.22e-01]
[-2.95e-02]
[ 1.12e-01]
[ 3.60e-01]
[ 7.27e-02]
[ 1.88e-01]
[ 2.52e-01]
[-6.02e-01]
[-1.38e+00]
[-7.67e-02]
[ 1.03e-01]
[ 7.91e-02]
[ 2.99e-01]
[-1.40e-01]



In [54]:
opti_x = sol['x']

In [51]:
## Assuming No Inequality Constraints

In [52]:
G2 = matrix(np.zeros((48,24) , dtype=float))

In [53]:
H2 = matrix([0.0 for i in range(48)])

In [55]:
sol2 = solvers.qp(A1, B1, G2, H2, C1, D1)

     pcost       dcost       gap    pres   dres
 0: -6.0622e-01 -6.0622e-01  5e+01  7e+00  7e-17
 1: -6.0622e-01 -6.0622e-01  5e-01  7e-02  6e-17
 2: -6.0622e-01 -6.0622e-01  5e-03  7e-04  5e-17
 3: -6.0622e-01 -6.0622e-01  5e-05  7e-06  4e-17
 4: -6.0622e-01 -6.0622e-01  5e-07  7e-08  4e-17
Optimal solution found.


In [57]:
opti_x_new = sol2['x']
print(opti_x_new)

[ 1.05e-02]
[ 4.79e-01]
[ 2.71e-01]
[ 1.06e-01]
[ 2.29e-01]
[ 7.29e-01]
[-4.83e-01]
[ 5.95e-02]
[-5.02e-01]
[-2.55e-01]
[ 1.22e-01]
[-2.95e-02]
[ 1.12e-01]
[ 3.60e-01]
[ 7.27e-02]
[ 1.88e-01]
[ 2.52e-01]
[-6.02e-01]
[-1.38e+00]
[-7.67e-02]
[ 1.03e-01]
[ 7.91e-02]
[ 2.99e-01]
[-1.40e-01]



In [102]:
sol2

{'x': <24x1 matrix, tc='d'>,
 'y': <1x1 matrix, tc='d'>,
 's': <24x1 matrix, tc='d'>,
 'z': <24x1 matrix, tc='d'>,
 'status': 'optimal',
 'gap': 2.4000000000000077e-07,
 'relative gap': 2.300634731420544e-07,
 'primal objective': -1.043190371432022,
 'dual objective': -1.043190371432022,
 'primal infeasibility': 4.89897948556637e-08,
 'dual infeasibility': 4.393134621982496e-17,
 'primal slack': 1.000000000000003e-08,
 'dual slack': 1.0,
 'iterations': 4}